api_version = "2025-04"

[[extensions]]
name = "t:name"
handle = "tiered"
type = "function"
uid = "bb3d26e9-015d-44db-96dd-c677a172c95b"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart_lines_discounts_generate_run"

  [[extensions.targeting]]
  target = "cart.delivery-options.discounts.generate.run"
  input_query = "src/cart_delivery_options_discounts_generate_run.graphql"
  export = "cart_delivery_options_discounts_generate_run"

  [extensions.build]
  command = "cargo build --target=wasm32-wasip1 --release"
  path = "target/wasm32-wasip1/release/tiered.wasm"
  watch = [ "src/**/*.rs" ]
